Check systemctl

diff --git a/debian/iputils-rdisc.postinst b/debian/iputils-rdisc.postinst
--- a/debian/iputils-rdisc.postinst
+++ b/debian/iputils-rdisc.postinst
@@ -8,16 +8,18 @@ if [ "$1" = configure ]; then
     # If we have setcap installed, try setting cap_net_raw+ep,
     # which allows us to install our binaries without the setuid
     # bit.
-    if command -v setcap > /dev/null; then
-        if setcap cap_net_raw,cap_net_admin+ep $PROGRAM; then
-            chmod u-s $PROGRAM
+    if ! which systemctl; then
+        if command -v setcap > /dev/null; then
+            if setcap cap_net_raw,cap_net_admin+ep $PROGRAM; then
+                chmod u-s $PROGRAM
+            else
+                echo "Setcap failed on $PROGRAM, falling back to setuid" >&2
+                chmod u+s $PROGRAM
+            fi
         else
-            echo "Setcap failed on $PROGRAM, falling back to setuid" >&2
+            echo "Setcap is not installed, falling back to setuid" >&2
             chmod u+s $PROGRAM
         fi
-    else
-        echo "Setcap is not installed, falling back to setuid" >&2
-        chmod u+s $PROGRAM
     fi
 fi
 echo OPTIONS=\"-s\" >> /etc/default/rdisc
